name: build push main image

on:
  push
  # push:
  #   tags:        
  #     - v**

jobs:
  main:
    runs-on: windows-latest
    steps:
  
      # Checkout the repo, fetch-depth:0 to include tags
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - name: 'Get Previous tag'
      #   id: previoustag
      #   uses: "WyriHaximus/github-action-get-previous-tag@v1"
      
      # # Get the last commit of the repo and the commit of the latest tag
      # - name: Set commit id variables
      #   id: vars
      #   run: |
      #     echo "::set-output name=latest_commit::$(git rev-parse HEAD)"
      #     echo "::set-output name=release_tagged_commit::$(git rev-list -n 1 ${{ steps.previoustag.outputs.tag }})"
      
      # # If they don't match cancel/fail the build
      # - uses: therussiankid92/gat@v1
      #   with:  
      #     assertion: should.equal  
      #     expected: ${{ steps.vars.outputs.latest_commit }}  
      #     actual: ${{ steps.vars.outputs.release_tagged_commit }}

      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: gsscogs/csvlint
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          directory: csvlint
          dockerfile: csvlint\Dockerfile
