name: build push main image

on:
  push
  # push:
  #   tags:        
  #     - v**

jobs:
  main:
    runs-on: windows-latest
    steps:
  
      # Checkout the repo, fetch-depth:0 to include tags
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: 'Get Previous tag'
      #   id: previoustag
      #   uses: "WyriHaximus/github-action-get-previous-tag@v1"
      
      # # Get the last commit of the repo and the commit of the latest tag
      # - name: Set commit id variables
      #   id: vars
      #   run: |
      #     echo "::set-output name=latest_commit::$(git rev-parse HEAD)"
      #     echo "::set-output name=release_tagged_commit::$(git rev-list -n 1 ${{ steps.previoustag.outputs.tag }})"
      
      # # If they don't match cancel/fail the build
      # - uses: therussiankid92/gat@v1
      #   with:  
      #     assertion: should.equal  
      #     expected: ${{ steps.vars.outputs.latest_commit }}  
      #     actual: ${{ steps.vars.outputs.release_tagged_commit }}

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build main
        uses: docker/build-push-action@v2
        id: docker_build_main
        with:
          context: .
          file: ./csvlint/Dockerfile
          push: true
          tags: |
            gsscogs/csvlint:latest

        #gsscogs/csvlint:${{ steps.previoustag.outputs.tag }}

      - name: Main Image digest
        run: echo ${{ steps.docker_build_main.outputs.digest }}