name: build push main image

on:
  push
  # push:
  #   tags:        
  #     - v**

jobs:
  main:
    runs-on: windows-latest
    steps:
  
      # Checkout the repo, fetch-depth:0 to include tags
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build + Deploy Windows Container
        run: |
          docker build --file=csvlint/Dockerfile -t csvlint-windows:test .
          docker push NAME:[windows-docker-images]


      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}