name: build push main image

on:
  push

jobs:
  main:
    runs-on: windows-latest
    steps:
  
      # Checkout the repo, fetch-depth:0 to include tags
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build + Deploy Windows Container
        run: |
          docker build --file=Dockerfile -t gsscogs/csvcubed-windows-build:latest .
          docker push gsscogs/csvcubed-windows-build:latest

